[env:esp32dev]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv

lib_deps =
    ; DS18B20 Temperature Sensor
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.11.0
    
    ; Standard Parallel LCD Library
    arduino-libraries/LiquidCrystal @ ^1.0.7
    
    ; Firebase ESP32 Client (Stable version)
    mobizt/Firebase ESP32 Client @ ^4.4.14

    ; WiFi Manager (captive portal setup)
    https://github.com/tzapu/WiFiManager.git
